name: eu_cbm_hat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipython
  - matplotlib
  - numexpr
  - numpy
  - pandas
  - pip
  - pyarrow
  - pyyaml
  - seaborn
  - simplejson
  - tqdm
  - pip:
    - autopaths>=1.6.0
    - libcbm
    - p_tqdm
    - plumbing>=2.11.1
    - pymarktex>=1.4.6
    - pystache
